---
abstract: 'JSON format for flux storages'
author:
  - 'Vyacheslav Matyukhin <me@berekuk.ru>'
build_requires:
  Flux::Storage::Memory: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Flux-Format-JSON
requires:
  Flux::Format: 0
  Flux::Simple: 0
  JSON: 0
  Moo: 0
resources:
  repository: git://github.com/berekuk/Flux-Format-JSON.git
version: 1.00
